# Generated by Django 5.2.7 on 2025-10-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0002_remove_user_year_level_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
