# Generated by Django 5.2.7 on 2025-10-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0003_adminprofile_full_name_studentprofile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='full_name',
        ),
    ]
