# Generated by Django 5.2.7 on 2025-10-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0004_remove_adminprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
