# Generated by Django 5.2.7 on 2025-11-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0008_studentprofile_completed_hours_evaluation'),
        ('interntrack_app', '0008_studentprofile_completed_hours_user_is_staff_and_more'),
    ]

    operations = [
    ]
