# Generated by Django 5.2.7 on 2025-11-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0009_studentprofile_completed_hours_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='completed_hours',
        ),
    ]
