# Generated by Django 5.2.7 on 2025-11-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0009_merge_20251110_1913'),
        ('interntrack_app', '0012_rename_score_evaluation_eval_score'),
    ]

    operations = [
    ]
