# Generated by Django 5.2.7 on 2025-12-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0015_remove_attendance_remarks_evaluation_eval_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='remarks',
        ),
    ]
