# Generated by Django 5.2.7 on 2025-12-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0016_remove_attendance_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='company',
            field=models.CharField(default='TestComp', max_length=100),
        ),
    ]
