# Generated by Django 5.2.7 on 2025-12-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0017_studentprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
