# Generated by Django 5.2.7 on 2025-12-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0019_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='company',
            field=models.CharField(default='TestComp', max_length=100),
        ),
    ]
