# Generated by Django 5.2.7 on 2025-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interntrack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('year_level', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student')], default='admin')),
            ],
        ),
    ]
